import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import '@radix-ui/themes/styles.css';
import AuthContext from '@/context/AuthContext';
import SWRConfigContext from '@/context/SWRConfigContext';
import clsx from 'clsx';
import ConditionalNavBar from '@/components/ConditionalNavBar';
import { ToastDescription } from '@radix-ui/react-toast';

const notoSans = Noto_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={clsx(notoSans.className)}>
        <Theme
          accentColor="crimson"
          grayColor="olive"
          radius="large"
          scaling="100%"
        >
          <AuthContext>
            <SWRConfigContext>
              <ConditionalNavBar />
              {/* Studio 페이지에서 NavBar 제외 */}
              {children}
              {/* <ThemePanel /> */}
              <Toaster>
                <ToastDescription>asdfasdf</ToastDescription>
              </Toaster>
            </SWRConfigContext>
          </AuthContext>
        </Theme>
      </body>
    </html>
  );
}
