import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import '@radix-ui/themes/styles.css';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSans.className}>
        <Theme accentColor="crimson" grayColor="olive" radius="large" scaling="100%">
          {children}
          {/* <ThemePanel /> */}
          <Toaster />
        </Theme>
      </body>
    </html>
  );
}

